name: "Static Analysis"
on: ["push", "pull_request"]
jobs:
  Static-Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "zulu"

      - name: Configure Linux runner
        run: echo "MAVEN_HOME=$(whereis mvn)" >> $GITHUB_ENV

      - name: Run Analysis
        run: mvn -V -B -U --no-transfer-progress clean verify
